version: '3'

services:
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile # Assuming the Dockerfile is named 'Dockerfile'
    # volumes:
    #   - ./client:/app/client
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: ["npm", "start"]
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile # Assuming the Dockerfile is named 'Dockerfile'
    # volumes:
    #   - ./server:/app/server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    command: ["node", "server.js"]

networks:
  default:
    driver: bridge